# Pipeline Azure DevOps avec agent auto-hébergé temporaire
# À utiliser en attendant l'approbation du parallélisme Microsoft

trigger:
- master
- main

pr:
- master
- main

# Utilisation d'un agent auto-hébergé au lieu d'un agent Microsoft
pool: 
  name: 'Default'  # Nom du pool d'agents auto-hébergés

variables:
  nodeVersion: '20.x'

stages:
- stage: QualityGate
  displayName: 'Quality Gate - Tests et Linting'
  jobs:
  - job: CodeQuality
    displayName: 'Code Quality Checks'
    steps:
    
    # Vérification que Node.js est installé
    - script: |
        node --version
        npm --version
      displayName: 'Check Node.js version'
    
    # Installation des dépendances
    - script: |
        npm ci
      displayName: 'Install dependencies'
    
    # Vérification ESLint
    - script: |
        npm run lint
      displayName: 'Run ESLint'
      continueOnError: false
    
    # Vérification TypeScript
    - script: |
        npm run type-check
      displayName: 'TypeScript type checking'
      continueOnError: false
    
    # Exécution des tests unitaires
    - script: |
        npm run test:unit run
      displayName: 'Run unit tests'
      continueOnError: false
    
    # Build de l'application
    - script: |
        npm run build
      displayName: 'Build application'
      continueOnError: false