# Pipeline corrigé - Utilise les agents Microsoft hébergés
trigger:
- master
- main

pr:
- master
- main

# IMPORTANT: Utiliser vmImage au lieu du pool Default
pool:
  vmImage: 'ubuntu-latest'

variables:
  nodeVersion: '20.x'

jobs:
- job: CodeQuality
  displayName: 'Code Quality Checks'
  steps:
  
  # Installation de Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodeVersion)
    displayName: 'Install Node.js $(nodeVersion)'
  
  # Installation des dépendances
  - script: npm ci
    displayName: 'Install dependencies'
    
  # Linting ESLint
  - script: npm run lint
    displayName: 'Run ESLint'
    continueOnError: false
  
  # Vérification TypeScript
  - script: npm run type-check
    displayName: 'TypeScript type checking'
    continueOnError: false
  
  # Tests unitaires
  - script: npm run test:unit run
    displayName: 'Run unit tests'
    continueOnError: false
  
  # Build de l'application
  - script: npm run build
    displayName: 'Build application'
    continueOnError: false
  
  # Message de succès
  - script: echo "✅ All quality checks passed!"
    displayName: 'Pipeline completed successfully'